src/main.js
There's no point in throwing all the information away and presenting
the user with a blank screen when we already have information that
we could be showing them.
https://phabricator.endlessm.com/T18569
=> main: Don't throw stuff away from model until we have replacements

src/main.js
https://phabricator.endlessm.com/T18974
=> Replace Number.MAX_INT with Number.MAX_VALUE

src/main.js
Layout information is now embedded into the model itself, so
there's no need to defer this until we add the card to the model.
Remove the code so that it doesn't confuse the reader.
https://phabricator.endlessm.com/T18891
=> main: Remove layoutIndex and deferred-construction logic

src/main.js
https://phabricator.endlessm.com/T18902
=> T18902: Don't trigger focus stealing prevention

src/modelOrdering.js
If there are enough cards the evergreen card wil always go
at the third position, otherwise it gets appended after
the other cards.
https://phabricator.endlessm.com/T19012
=> Make sure evergreen apps card always show in the feed

tests/js/testModelOrdering.js
https://phabricator.endlessm.com/T19012
=> tests: Add test for appending the word/quote card

src/main.js
Otherwise we'll attempt to mutate this._window
https://phabricator.endlessm.com/T18975
=> main: Disconnect monitor change signals when window is destroyed

src/main.js
https://phabricator.endlessm.com/T18895
=> Artwork: position the thumbnail on the right side of the card

Makefile.am
https://phabricator.endlessm.com/T19314
=> GSetting: gschema.xml.in file should go in EXTRA_DIST

src/main.js
This fixes an error discovered with Video content.
https://phabricator.endlessm.com/T19957
=> VideoCards: port to new promisifyGIO code

src/main.js, src/stores.js
A follow-on from #73 
https://phabricator.endlessm.com/T21020
=> T21020: Additional Cleanups

src/main.js
https://phabricator.endlessm.com/T21260
=> main: Defend against EknServices not having a first_date prop on artwork

data/app-content-description.ui, data/application.css
As per design feedback
https://phabricator.endlessm.com/T18896
=> css: Make content date text black and 14px

Makefile.am, configure.ac, libfeed/feed-text-sanitization.c, libfeed/feed-text-sanitization.h, src/textSanitization.js
This is just a trial run of getting C code up and running in the Discovery Feed. Most of the work here is just necessary build-system stuff.
https://phabricator.endlessm.com/T21130
=> feed: Port synopsis sanitization to C

libfeed/feed-knowledge-app-video-card-store.c
https://phabricator.endlessm.com/T21798
=> VideoCardStore: fix copy and paste error for type

libfeed/feed-model-ordering.c
Restructure the model ordering code to make it a bit clearer as to what it is doing.
Add comments to each of the fields specifying what their roles are in the algorithm, as it is a little tricky to get one's head around.
https://phabricator.endlessm.com/T21130
=> T21130: Clarify model ordering code

src/main.js
https://phabricator.endlessm.com/T21800
=> main: Explicitly quit the application once we call a content-load func

src/main.js
Just immediately quit when we click on the card.
https://phabricator.endlessm.com/T21800
=> main: Don't wait for the shell to report application load status

src/main.js
https://phabricator.endlessm.com/T21798
=> main: Make video card content preview 16:9 (height of 470)

tests/js/testDiscoveryFeed.js
https://phabricator.endlessm.com/T21878
=> T21878: Add tests for 60-character textSanitization rules

src/main.js, src/stores.js, src/textSanitization.js, tests/js/testModelOrdering.js
https://phabricator.endlessm.com/T22542
=> feed: Use ContentFeed symbol
